
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/TopBar";
import Sidebar from "@/components/Sidebar";
import { Suspense } from "react";
import { ThemeProvider } from "@/components/theme-provider";
import Sidebars from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ThemeProvider attribute='class' defaultTheme="system" enableSystem disableTransitionOnChange>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased grid grid-cols-5`}
        >
          <div className="col-span-1   h-[100vh] fixed top-0 left-0">
            <Sidebars />
          </div>
          <div className="col-span-4 col-start-2  ">

            {children}
          </div>


        </body>
      </ThemeProvider>
    </html>
  );
}
